# Generated by Django 4.2.5 on 2023-09-22 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_item_item_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='item_img',
            field=models.CharField(default='https://imgs.search.brave.com/N9JbF0zYUgn4lLcmuNFkGc7UdGzd8jXgH2NrwvYPMW8/rs:fit:860:0:0/g:ce/aHR0cHM6Ly90NC5m/dGNkbi5uZXQvanBn/LzAzLzE1LzE4LzA5/LzM2MF9GXzMxNTE4/MDkzMl9yaGlYRnJK/TjI3elhDQ2RyZ3g4/VjVHV2JMZDl6VEhI/QS5qcGc', max_length=500),
        ),
    ]
